export const ErrorCode = {
  WRONG_CREDENTIALS: 'WRONG_CREDENTIALS',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
  COMPANY_SUSPENDED: 'COMPANY_SUSPENDED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  CODE_TAKEN: 'CODE_TAKEN',
  NAME_TAKEN: 'NAME_TAKEN',
  LOCATION_REQUIRED: 'LOCATION_REQUIRED',
  DATE_PAST: 'DATE_PAST',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
